/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DriverStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'bicycle' : IDL.Null,
  'scooter' : IDL.Null,
});
export const DriverProfile = IDL.Record({
  'status' : DriverStatus,
  'vehicleType' : VehicleType,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const DriverWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : DriverProfile,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDriversWithPrincipals' : IDL.Func(
      [],
      [IDL.Vec(DriverWithPrincipal)],
      ['query'],
    ),
  'getCallerDriverProfile' : IDL.Func([], [IDL.Opt(DriverProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DriverProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerDriver' : IDL.Func([DriverProfile], [], []),
  'saveDriverProfile' : IDL.Func([DriverProfile], [], []),
  'updateDriverStatus' : IDL.Func([IDL.Principal, DriverStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DriverStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'bicycle' : IDL.Null,
    'scooter' : IDL.Null,
  });
  const DriverProfile = IDL.Record({
    'status' : DriverStatus,
    'vehicleType' : VehicleType,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DriverWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : DriverProfile,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDriversWithPrincipals' : IDL.Func(
        [],
        [IDL.Vec(DriverWithPrincipal)],
        ['query'],
      ),
    'getCallerDriverProfile' : IDL.Func(
        [],
        [IDL.Opt(DriverProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DriverProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerDriver' : IDL.Func([DriverProfile], [], []),
    'saveDriverProfile' : IDL.Func([DriverProfile], [], []),
    'updateDriverStatus' : IDL.Func([IDL.Principal, DriverStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };